language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
# command to install dependencies
install:
  # - pip install -r requirements.txt
  - python setup.py install
# travis uses an older version of pytest for python 3.4
  - pip install --upgrade pytest
# command to run tests
script: python setup.py test
# which branch to test
branches:
  only:
    - master
    - develop